services:
  - type: web
    name: freddy-crypto-signals
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 8501
        
